const pdfGenerator = require('pdfkit');
const fs = require('fs');

class DailyReportGenerator {
    constructor(date, branch, report) {
        this.date = date;
        this.branch = branch;
        this.report = report;
    }

    generateHeaders(doc) {
        //put the icon
        doc.image('../front-end/components/assets/medime_icon.png', 30, 0, { width: 200});
        doc.fillColor('#000');
        doc.fontSize(20);
        doc.text('DAILY REPORT', 275, 50, {align: 'right', bold: true});
        doc.fontSize(15);
        doc.text(`Date: ${this.date.toDateString()}`, {align: 'right'});
        doc.text(`Branch Address: ${this.branch[0].address}`, {align: 'right'});
        doc.moveDown();
        const beginningOfPage = 50;
        const endOfPage = 550;

        doc.moveTo(beginningOfPage, 200);
        doc.lineTo(endOfPage,200);
        doc.stroke();

        doc.fontSize(10);
        doc.text('This report is generated by the end of the day.', 50, 210);
        doc.moveTo(beginningOfPage, 250);
        doc.lineTo(endOfPage, 250);
        doc.stroke();
    }

    generateTable(doc) {
        const tableTop = 270;
        const productNameX = 50;
        const priceX = 220;
        const quantityX = 340;
        const amountX = 480;
        doc.fontSize(15);
        doc.text('Product Name', productNameX, tableTop);
        doc.text('Price', priceX, tableTop);
        doc.text('Quantity', quantityX, tableTop);
        doc.text('Amount', amountX, tableTop);

        const items = this.report.rows;
        let i = 0;

        for (i = 0; i < this.report.length; i++) {
            const item = this.report[i];
            const y = tableTop + (i+1)*25;
            doc.fontSize(15);
            doc.text(item.product_name, productNameX, y);
            doc.text(item.price, priceX, y);
            doc.text(item.total_quantity, quantityX, y);
            doc.text(item.price * item.total_quantity, amountX, y);
        }
    }

    generateFooter(doc) {
        doc.fontSize(10);
        doc.text('End of Report.', 50, 700, { align: 'center'});
    }

    generate(doc) {
        // let output = new pdfGenerator;
        // console.log(this.report);
        // const fileName = 'src/back-end/daily_report/daily_report.pdf';
        // output.pipe(fs.createWriteStream(fileName));
        this.generateHeaders(doc);
        doc.moveDown();
        this.generateTable(doc);
        this.generateFooter(doc);
        // output.end()
    }
}

module.exports = DailyReportGenerator;
