const pdfGenerator = require('pdfkit');
const fs = require('fs');
// const MonthlyReportLineGraph = require('./MonthlyReportLineGraph.js');

class MonthlyReportGenerator {
    constructor(month, year, branch) {
        this.month = month;
        this.year = year;
        this.branch = branch;
    }
    generateHeaders(doc) {
        //put the icon
        doc.image('../front-end/components/assets/medime_icon.png', 30, 0, { width: 200});
        doc.fillColor('#000');
        doc.fontSize(20);
        doc.text('MONTHLY REPORT', 275, 50, {align: 'right', bold: true});
        doc.fontSize(15);
        doc.text(`Month: ${this.month}`, {align: 'right'});
        doc.text(`Year: ${this.year}`, {align: 'right'});
        doc.text(`Branch address: ${this.branch[0].address}`, {align: 'right'});
        doc.moveDown();
        const beginningOfPage = 50;
        const endOfPage = 550;

        doc.moveTo(beginningOfPage, 200);
        doc.lineTo(endOfPage,200);
        doc.stroke();

        doc.fontSize(10);
        doc.text('This report is generated by the end of the month.', 50, 210);
        doc.moveTo(beginningOfPage, 250);
        doc.lineTo(endOfPage, 250);
        doc.stroke();
    }

    async generateChart(doc, chart1, chart2) {
        // const chart = new MonthlyReportLineGraph(this.export_data, this.import_data);
        // const chart1 = await chart.generateSalesLineGraph();
        // const chart2 = await chart.generateImportLineGraph();
        doc.image(chart1, 30, 260, {width: 400});
        doc.image(chart2, 150, 500, {width: 400});
    }

    generateFooter(doc) {
        doc.fontSize(10);
        doc.text('End of Report.', 50, 700, { align: 'center'});
    }

    generate(doc, chart1, chart2) {
        // let output = new pdfGenerator;
        // console.log(this.report);
        // const fileName = 'src/back-end/monthly_report/monthly_report.pdf';
        // output.pipe(fs.createWriteStream(fileName));
        this.generateHeaders(doc);
        doc.moveDown();
        this.generateChart(doc, chart1, chart2);
        this.generateFooter(doc);
        // output.end()
    }
}

module.exports = MonthlyReportGenerator;

// let doc = new pdfGenerator;
// const fileName = 'src/back-end/monthly_report/test.pdf';
// doc.pipe(fs.createWriteStream(fileName));
// doc.image('src/front-end/components/assets/medime_icon.png', 30, 0, { width: 200});
// doc.fillColor('#000');
// doc.fontSize(20);
// doc.text('MONTHLY REPORT', 275, 50, {align: 'right', bold: true});
// doc.moveDown();
// const beginningOfPage = 50;
// const endOfPage = 550;

// doc.moveTo(beginningOfPage, 200);
// doc.lineTo(endOfPage,200);
// doc.stroke();

// doc.fontSize(10);
// doc.text('This report is generated by the end of the month.', 50, 210);
// doc.moveTo(beginningOfPage, 250);
// doc.lineTo(endOfPage, 250);
// doc.stroke();

// doc.moveDown();
// doc.image('src/back-end/monthly_report/chart.png', 30, 260, { width: 400});
// doc.image('src/back-end/monthly_report/chart.png', 150, 500, { width: 400});

// doc.end();